-- ═══════════════════════════════════════════════════════════════════════════
-- V1__init.sql — Phase 4: Memory Layer initial schema
-- ═══════════════════════════════════════════════════════════════════════════
--
-- MERN/Next.js analogy:
--   This is the equivalent of a Prisma migration file or a Knex migration.
--   Flyway runs this exactly once (tracked by flyway_schema_history table).
--   Subsequent changes go in V2, V3, etc. — never edit a deployed version.
--
-- Syntax note:
--   Uses SQL standard GENERATED BY DEFAULT AS IDENTITY (ISO/IEC 9075-2),
--   supported by both H2 2.x (dev) and PostgreSQL 10+ (prod Phase 10).
--   Avoids BIGSERIAL which is PostgreSQL-specific.
--
-- Book ref: Chapter 7 — Memory
--   Three tables map to the three memory categories in the book:
--     conversation_message → short-term / session memory
--     agent_note           → long-term / episodic memory
--     user_profile         → long-term / semantic memory (user facts)
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Short-term / conversation memory ─────────────────────────────────────
-- Stores every message exchanged in a chat session (user + assistant turns).
-- MERN analogy: a messages collection in MongoDB, or a Prisma Message model.
CREATE TABLE conversation_message (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(64)  NOT NULL,
    role       VARCHAR(16)  NOT NULL,   -- 'user' | 'assistant' | 'tool'
    content    TEXT         NOT NULL,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_conv_msg_user_id ON conversation_message (user_id, created_at DESC);

-- ── Long-term / semantic memory — user profile ───────────────────────────
-- One row per user; stores stable preferences and goals.
-- MERN analogy: a users collection with a profile sub-document.
CREATE TABLE user_profile (
    user_id       VARCHAR(64)  PRIMARY KEY,
    display_name  VARCHAR(128),
    dietary_goals TEXT,
    restrictions  TEXT,
    updated_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── Long-term / episodic memory — agent notes ────────────────────────────
-- Free-text notes generated by agents during sessions.
-- Phase 4: keyword-searched. Phase 10: replaced by pgvector similarity search.
-- MERN analogy: a notes collection filtered by userId.
CREATE TABLE agent_note (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(64)  NOT NULL,
    note_type  VARCHAR(32),             -- e.g. 'coaching', 'research', 'preference'
    content    TEXT         NOT NULL,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_agent_note_user_id ON agent_note (user_id);
